### ISSUE TITLE
Adapter does not receive message of a custom scheme

### ISSUE THREAD

**Issue by EricNeid** [DRIVER-EU/java-test-bed-adapter#10]
I noticed this during my tests. The first time my adapter writes to a fresh testbed instance, he does not receive said messages.

Workflow:

- Subscribe to my topic
- Produce message on this topic
- Wait for the message to be received <-never happens

The message are of a custom scheme, so the adapter needs to register them. Maybe this is related to the problem? I also tried to send the message before a subscription, but this does not make a difference.  On my second testrun (new Adapter instance, but Schema is already registered), everything works as expected.

**Comment by PHameete** [comment]
Hey Eric! 

I ran into this as well, and was also confused by this. I figured out what is going on however:

If testing a send/receive interaction with a producer/consumer for example send CAP receive own CAP it is important to allow the consumer some time to retrieve partitions before sending. This can typically take 15 seconds. 

If you don’t do this the consumer will start consuming from the offset after the CAP message you just sent, and therefore never receive it. Ideally for a test case the producer returns the offset of the producer message, and the consumer fetches the message at that offset to perform the test. Unfortunately our adapter hides this Kafka functionality making it unavailable for tests.

So as a concrete fix for your issue: Let your test sleep for ~15 seconds after starting the consumer, before starting the producer that will produce the message. For example look at the tests I wrote:

https://github.com/DRIVER-EU/java-test-bed-adapter/blob/integration-tests/testbedadapter/src/test/java/eu/driver/adapter/ittest/JavaAdapterIT.java

@thoobr 
We should probably figure out a way to change the behavior of the adapter or change the API so that it works as expected. In this case you would expect to receive your own message, but because there is a race condition (consumer fetching the offset vs producer publishing the message) this is not the case.

**Comment by EricNeid** [comment]
Thanks. That worked! However, running all my tests now takes quite some time. I agree that receiving messages with a given offset would be helpful for testing.

**Comment by PHameete** [comment]
Yeah I think 15 secs is a bit much but I want to give it some slack when running on a Travis VM where there are not a lot of resources available for the test-bed brokers :-)

Alternatively the initialization of the Consumer could block until it has retrieved its partition info and is ready to receive.

For unit tests using the offsets would be best, agreed. But we'd have to discuss if we want to expose this functionality in the API, or perhaps provide an extended consumer/producer with this functionality.

**Comment by PHameete** [comment]
I'll close this. Slightly rephrased it as a concrete problem so we can continue in #11
